[package]
name = "vozeb-pro-desktop"
version = "0.0.7"
description = "VOZEB PRO desktop shell"
authors = ["VOZEB PRO"]
edition = "2021"

[lib]
name = "vozeb_pro_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
